name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]    

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'
    - name: Install pnpm
      run: npm install -g pnpm
    - name: Install dependenies
      run: pnpm install
    - name: Build
      run: pnpm run build        
    - name: Test
      run: pnpm test
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}